name: 🛠️ Tool Submission
description: Submit a tool for integration into the AI PM Exploration Toolkit
title: "[TOOL] "
labels: ["tool-submission", "needs-review"]
body:
  - type: markdown
    attributes:
      value: |
        # Tool Submission for AI PM Exploration Toolkit
        
        Thank you for contributing to the 4E Framework journey! This template helps us evaluate how your tool supports strategic product managers in their path from AI-curious to AI-confident.
        
        **📖 Before submitting**: Please review our [Contributing Guidelines](../../CONTRIBUTING.md) to ensure your tool meets our requirements.

  - type: input
    id: tool-name
    attributes:
      label: Tool Name
      description: What is the name of the tool?
      placeholder: "e.g., OpenBB Terminal"
    validations:
      required: true

  - type: input
    id: tool-homepage
    attributes:
      label: Homepage/Repository
      description: Link to the tool's main website or repository
      placeholder: "https://github.com/..."
    validations:
      required: true

  - type: dropdown
    id: license
    attributes:
      label: License
      description: What license does this tool use?
      options:
        - MIT
        - Apache 2.0
        - GPL v3
        - GPL v2
        - BSD 3-Clause
        - BSD 2-Clause
        - Mozilla Public License 2.0
        - Other OSI-approved
        - Source-available (not OSI)
    validations:
      required: true

  - type: dropdown
    id: installation
    attributes:
      label: Installation Method
      description: How is this tool typically installed?
      options:
        - pip (Python)
        - npm (Node.js)
        - brew (Homebrew)
        - docker
        - Binary download
        - Source compilation
        - Other
    validations:
      required: true

  - type: checkboxes
    id: four-e-alignment
    attributes:
      label: 4E Framework Alignment
      description: Which of the Four Pillars does your tool support? (Select all that apply)
      options:
        - label: "🎓 **Education** - Helps PMs learn AI through hands-on practice"
        - label: "🧪 **Experimentation** - Enables hypothesis testing with synthetic data"
        - label: "🔍 **Exploration** - Facilitates discovery of AI possibilities"
        - label: "📊 **Explanation** - Creates artifacts for stakeholder buy-in"

  - type: textarea
    id: education-support
    attributes:
      label: Education Support (if applicable)
      description: How does this tool help PMs learn AI concepts?
      placeholder: "Explain specific educational value, safe learning environment features, hands-on capabilities..."

  - type: textarea
    id: experimentation-support
    attributes:
      label: Experimentation Support (if applicable)
      description: How does this tool enable hypothesis testing and evidence generation?
      placeholder: "Describe synthetic data capabilities, testing frameworks, validation features..."

  - type: textarea
    id: exploration-support
    attributes:
      label: Exploration Support (if applicable)
      description: How does this tool facilitate discovery and free-form tinkering?
      placeholder: "Explain discovery features, visual interfaces, exploration workflows..."

  - type: textarea
    id: explanation-support
    attributes:
      label: Explanation Support (if applicable)
      description: How does this tool help create compelling stakeholder presentations?
      placeholder: "Describe visualization, reporting, storytelling, or demonstration capabilities..."

  - type: textarea
    id: pm-scenarios
    attributes:
      label: PM Use Cases
      description: Provide 2+ realistic scenarios where PMs would use this tool
      placeholder: |
        **Scenario 1**: [Describe specific PM challenge and how tool solves it]
        **Scenario 2**: [Describe another PM challenge and solution]
    validations:
      required: true

  - type: textarea
    id: pol-probe-support
    attributes:
      label: Proof-of-Life Probe Support
      description: How does this tool support the PoL Probe methodology?
      placeholder: "Explain how the tool enables lightweight, disposable, brutally honest prototypes that tell harsh truths..."
    validations:
      required: true

  - type: dropdown
    id: setup-complexity
    attributes:
      label: Setup Complexity
      description: How complex is the installation and setup process?
      options:
        - Simple (< 5 minutes, minimal dependencies)
        - Moderate (5-15 minutes, some configuration)
        - Complex (> 15 minutes, significant setup)
    validations:
      required: true

  - type: checkboxes
    id: privacy-requirements
    attributes:
      label: Privacy & Security
      description: Privacy and security compliance (check all that apply)
      options:
        - label: "✅ Core features work 100% offline"
        - label: "✅ No mandatory external API calls for basic functionality"
        - label: "✅ Optional cloud features require explicit user consent"
        - label: "✅ Clear data handling practices documented"

  - type: textarea
    id: data-privacy-statement
    attributes:
      label: Data Privacy Statement
      description: "**Required for AI tools**: How does this tool handle user data, especially sensitive information?"
      placeholder: "Describe data collection, storage, processing, and any AI model interactions..."

  - type: textarea
    id: ai-bias-ethics
    attributes:
      label: AI Bias & Ethics Statement
      description: "**Required for AI tools**: How does this tool address AI bias and ethical considerations?"
      placeholder: "Describe bias mitigation, ethical safeguards, known limitations, responsible use guidelines..."

  - type: input
    id: suggested-command
    attributes:
      label: Suggested CLI Command
      description: What CLI command would you suggest for this tool?
      placeholder: "aipm_toolname"
    validations:
      required: true

  - type: dropdown
    id: workspace-category
    attributes:
      label: Workspace Category
      description: Which workspace directory would be most appropriate?
      options:
        - market-research
        - competitive-intel
        - experiments
        - prototypes
        - synthetic-data
        - monitoring
        - design
        - notebooks
        - workflow-tools
        - prompt-testing
        - obsidian-vault
        - Other (specify in additional context)

  - type: checkboxes
    id: quality-checklist
    attributes:
      label: Quality Assurance Checklist
      description: Quality requirements (check all that apply)
      options:
        - label: "📖 Comprehensive documentation with installation guide"
        - label: "🔧 Working demo/example that runs in < 5 minutes"
        - label: "🔄 Active maintenance within last 2 years"
        - label: "🛡️ Error handling and graceful degradation"
        - label: "🎯 Non-redundant OR clear value-add over existing tools"

  - type: textarea
    id: integration-details
    attributes:
      label: Integration Details
      description: Any special considerations for integrating this tool?
      placeholder: "Dependencies, conflicts, configuration requirements, workspace setup..."

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Anything else you'd like to add about this tool submission?

  - type: checkboxes
    id: submission-checklist
    attributes:
      label: Submission Checklist
      description: Final checklist before submission
      options:
        - label: "✅ I have read the [Contributing Guidelines](../../CONTRIBUTING.md)"
        - label: "✅ This tool clearly supports strategic product managers"
        - label: "✅ This tool aligns with at least one 4E Framework pillar"
        - label: "✅ I have provided realistic PM use cases"
        - label: "✅ I understand the three-tier review process"
        - label: "✅ I am willing to engage in the integration process"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        
        **Next Steps:**
        1. **Review Process**: Your submission will go through automated checks, 4E framework review, and community testing
        2. **Timeline**: Expect 1-2 weeks for simple tools, 3-4 weeks for complex integrations
        3. **Collaboration**: We may ask questions or request changes during the integration process
        4. **Recognition**: Successful contributions are recognized in our README and community
        
        Thank you for contributing to the AI PM Exploration Toolkit! 🚀