name: 💡 Tool Suggestion
description: Suggest a tool for potential integration (for non-technical users)
title: "[SUGGESTION] "
labels: ["tool-suggestion", "community-input"]
body:
  - type: markdown
    attributes:
      value: |
        # Tool Suggestion for AI PM Exploration Toolkit
        
        Have you found a tool that could help strategic product managers in their 4E journey? We'd love to hear about it! Community members may help with the technical integration.

  - type: input
    id: tool-name
    attributes:
      label: Tool Name
      description: What is the name of the tool you'd like to suggest?
      placeholder: "e.g., Example Tool"
    validations:
      required: true

  - type: input
    id: tool-link
    attributes:
      label: Tool Website/Link
      description: Where can we find this tool?
      placeholder: "https://..."

  - type: checkboxes
    id: four-e-potential
    attributes:
      label: 4E Framework Potential
      description: Which of the Four Pillars might this tool support?
      options:
        - label: "🎓 **Education** - Could help PMs learn AI concepts"
        - label: "🧪 **Experimentation** - Could enable testing with data"
        - label: "🔍 **Exploration** - Could help discover AI possibilities"
        - label: "📊 **Explanation** - Could create stakeholder presentations"
        - label: "❓ **Not sure** - Seems valuable but unclear how it fits"

  - type: textarea
    id: why-valuable
    attributes:
      label: Why is this tool valuable for PMs?
      description: What specific problem would this solve for product managers?
      placeholder: "Describe the PM challenge this tool could address..."
    validations:
      required: true

  - type: textarea
    id: how-discovered
    attributes:
      label: How did you discover this tool?
      description: Context about where/how you found it
      placeholder: "Found it while researching X, saw it recommended by Y, used it for Z..."

  - type: textarea
    id: pm-context
    attributes:
      label: PM Context
      description: How would you envision PMs using this in their PoL Probe work?
      placeholder: "PMs could use this to... It would help with... It solves the problem of..."

  - type: checkboxes
    id: basic-requirements
    attributes:
      label: Basic Requirements (if known)
      description: Check if you know these details about the tool
      options:
        - label: "🆓 Appears to be free or freemium"
        - label: "🏠 Seems to work offline or locally"
        - label: "📖 Has public documentation"
        - label: "🔒 Appears to respect user privacy"
        - label: "❓ Not sure about these requirements"

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Anything else you'd like to share about this tool?

  - type: checkboxes
    id: suggestion-checklist
    attributes:
      label: Suggestion Checklist
      options:
        - label: "✅ This tool could genuinely help strategic product managers"
        - label: "✅ I believe this aligns with the 4E Framework mission"
        - label: "✅ I'm not aware of this tool already being in the toolkit"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        
        **What happens next:**
        - Community members will evaluate the suggestion
        - If there's interest, someone may volunteer to create a full submission
        - We'll keep you updated on any progress
        - Great suggestions help make the toolkit better for all PMs!
        
        Thank you for helping improve the AI PM Exploration Toolkit! 🌟