# Docker Compose for n8n workflow automation

services:
  aipm-n8n:
    image: n8nio/n8n:latest
    container_name: aipm-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=UTC
      - N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN=true
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      - N8N_TEMPLATES_ENABLED=false
      - N8N_ONBOARDING_FLOW_DISABLED=true
      - N8N_USER_MANAGEMENT_DISABLED=true
    volumes:
      - aipm_n8n_data:/home/node/.n8n
    networks:
      - aipm_workflow_network
    labels:
      - "ai-pm-toolkit.service=n8n"
      - "ai-pm-toolkit.description=Visual workflow automation"
      - "ai-pm-toolkit.url=http://localhost:5678"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 5678 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  aipm_n8n_data:
    driver: local

networks:
  aipm_workflow_network:
    external: true
    name: aipm_workflow_network